# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='news_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.News'),
        ),
    ]
